// Code generated by "stringer -type ABNodeStatus"; DO NOT EDIT

package alphaYon

import "fmt"

const _ABNodeStatus_name = "WINNINGLOSINGUNKNOWN"

var _ABNodeStatus_index = [...]uint8{0, 7, 13, 20}

func (i ABNodeStatus) String() string {
	if i < 0 || i >= ABNodeStatus(len(_ABNodeStatus_index)-1) {
		return fmt.Sprintf("ABNodeStatus(%d)", i)
	}
	return _ABNodeStatus_name[_ABNodeStatus_index[i]:_ABNodeStatus_index[i+1]]
}
